<a href="https://colab.research.google.com/github/Sourabhkaverappa15/ML-projects/blob/main/Diabetes_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#input
input_data=(1,89,66,23,94,28.1,0.167,21)
input_array=np.asarray(input_data)

#reshape for 1 instance
input_array_reshaped=input_array.reshape(1,-1)

#standardise
input_array_std=scaler.transform(input_array_reshaped)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

##Importing the dependencies

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

## Data Collection and Analysis

In [4]:
df=pd.read_csv('/content/diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
df.shape

(768, 9)

In [6]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0 - non diabetic
 1 - diabetic

In [7]:
df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [8]:
x=df.drop(columns='Outcome',axis=1)
y=df['Outcome']

In [9]:
#pre processing
scaler=StandardScaler()
scaler.fit(x)
standardized_data=scaler.transform(x)

In [10]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [11]:
x=standardized_data
y=df['Outcome']

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5, stratify=y,random_state=2)

## Training the model

In [23]:
model=svm.SVC(kernel='linear')

In [24]:
model.fit(x_train,y_train)

SVC(kernel='linear')

## Evaluation and accuracy

In [25]:
#accuracy of train data
y_train_prediction=model.predict(x_train)
train_accuracy=accuracy_score(y_train_prediction,y_train)
print(train_accuracy)

0.7734375

In [26]:
#accuracy of test data
y_test_pred=model.predict(x_test)
test_accuracy=accuracy_score(y_test_pred,y_test)
print(test_accuracy)

0.7708333333333334

In [33]:
#input
input_data=(1,89,66,23,94,28.1,0.167,21)
input_array=np.asarray(input_data)

#reshape for 1 instance
input_array_reshaped=input_array.reshape(1,-1)

#standardise
input_array_std=scaler.transform(input_array_reshaped)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [35]:
prediction=model.predict(input_array_std)

prediction

array([0])